### ISSUE TITLE
Project Admin

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Anamaya/.github#1]
- [x] Create to sheet to store all Passwords
- [x] Update the readme to include pass sheet
- [x] Add a service registry to .github
- [x] Create a email ID
- [x] Setup GitHub Account with above email ID
- [x] Setup Vercel Account with GitHub created above

**Comment by geeky-abhishek** [comment]
@singhalkarun can you provide the ETA for step 3rd ?

**Comment by singhalkarun** [comment]
Added. I'll keep updating as we deploy more services.
